---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    pgp: >-
      F2B7F017852BF3D6D9D4341E6927A3487B629E14
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    pgp: >-
      9ADCC5768BD3FBED5FD5A1BAFD5A1E4F75E66921,
      F2B7F017852BF3D6D9D4341E6927A3487B629E14
