---
- hosts:
    - all
  become: true
  gather_facts: true
  any_errors_fatal: true
  vars:
    username: "<enterusernamehere"
    newpassword: "<enterpasswordhere>"
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  tasks:
    - name: Change user password
      user:
        name: "{{ username }}"
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"
