---

- name: test for cgroup_enable=memory
  command: 'grep "cgroup_enable=memory cgroup_memory=1" /boot/firmware/cmdline.txt'
  register: cgroup_group
  ignore_errors: yes

- name: add cgroup_enable=memory cgroup_memory=1 to cmdline.txt
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: True
    state: present
    regexp: '(.*)$'
    line: '\1 cgroup_enable=memory cgroup_memory=1'
  when: cgroup_group.rc == 1

- name: add overlay to modules to load
  lineinfile:
    path: /etc/modules
    line: overlay

- name: reboot the servers to apply cgroup change
  reboot:
    reboot_timeout: 3600