---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.6
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mon:
    count: 3
    allowMultiplePerNode: false
  placement:
    all:
      tolerations:
        - operator: "Exists"
  monitoring:
    enabled: false
    rulesNamespace: rook-ceph
  crashCollector:
    disable: false
  cleanupPolicy:
    confirmation: ""
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
  mgr:
    count: 2
    modules:
      - name: pg_autoscaler
        enabled: true
  dashboard:
    enabled: true
    port: 7000
    ssl: false
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
  resources:
    mon:
      requests:
        cpu: 35m
        memory: 800Mi
      limits:
        memory: 1024Mi
    osd:
      requests:
        cpu: 35m
        memory: 2048Mi
      limits:
        memory: 4096Mi
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      osdsPerDevice: "1"
    nodes:
      - name: "aprp01"
        devices:
        - name: "sda"
      - name: "aprp02"
        devices:
        - name: "sda"
      - name: "aprp03"
        devices:
        - name: "sda"
      - name: "aprp04"
        devices:
        - name: "sda"
      - name: "aprp05"
        devices:
        - name: "sda"
      - name: "aprp06"
        devices:
        - name: "sda"
      - name: "aprp07"
        devices:
        - name: "sda"
      - name: "aprp08"
        devices:
        - name: "sda"
      - name: "aprp09"
        devices:
        - name: "sda"
      - name: "aprp10"
        devices:
        - name: "sda"
      - name: "aprp11"
        devices:
        - name: "sda"
      - name: "aprp12"
        devices:
         - name: "sda"
