---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
apiVersion: v1
data:
  .dockerconfigjson: "${SECRET_DOCKER_CONFIG}"
kind: Secret
metadata:

  name: regcred
  namespace: cert-manager
type: kubernetes.io/dockerconfigjson
