---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system


---
apiVersion: v1
data:
  .dockerconfigjson: "${SECRET_DOCKER_CONFIG}"
kind: Secret
metadata:

  name: regcred
  namespace: metallb-system
type: kubernetes.io/dockerconfigjson
