---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph

---
apiVersion: v1
data:
  .dockerconfigjson: "${SECRET_DOCKER_CONFIG}"
kind: Secret
metadata:

  name: regcred
  namespace: rook-ceph
type: kubernetes.io/dockerconfigjson
