---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-cephs
  resources:
    requests:
      storage: 128Mi
